[33m2025-08-03 17:12:07.050 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:07.051 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:07.052 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:07.054 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:07.055 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:07.055 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:07.056 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:12.654 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:12:13.448 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[31m2025-08-03 17:12:34.584 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/d52aa0e.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
    ...<2 lines>...
    )
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/d52aa0e.zip[0m
[31m2025-08-03 17:12:34.588 ERROR (MainThread) [custom_components.hacs] [<Integration blakinio/thesslagreen>] Failed to download zipball
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 631, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 677, in download_repository_zip
    raise HacsException(f"[{self}] Failed to download zipball")
custom_components.hacs.exceptions.HacsException: [<Integration blakinio/thesslagreen>] Failed to download zipball[0m
[33m2025-08-03 17:12:38.045 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.046 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.048 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.049 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.050 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.051 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.053 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.054 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.055 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.065 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.066 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.067 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:38.068 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:12:43.265 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:12:43.266 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:13:04.224 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.podbitka2 are missing or not currently available[0m
[33m2025-08-03 17:13:12.660 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:13:13.444 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:13:43.259 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:13:43.261 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:14:12.686 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:14:13.479 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[31m2025-08-03 17:14:26.778 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Korytarz piƒôtro - przechod√≥wka' failed to setup triggers and has been disabled: Unknown device 'd6c41ce869f30ddc50c06f7d34708a00'[0m
[31m2025-08-03 17:14:26.779 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:14:26.780 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Jadalnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:14:26.781 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia halogeny' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:14:26.781 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Klatka przechod√≥wka' failed to setup actions and has been disabled: Unknown device '90048d596e6505d2699c9ea5cdc03f68'[0m
[31m2025-08-03 17:14:26.793 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'PKinkiet wiatrolap wejscie' failed to setup actions and has been disabled: Unknown device '4ff87fbffeaff04d6c4136fed22e06c4'[0m
[31m2025-08-03 17:14:26.795 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka prz√≥d' failed to setup actions and has been disabled: Unknown device '58f919db54b4be16b7dc704993322ae1'[0m
[31m2025-08-03 17:14:26.796 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Sypialnia' failed to setup actions and has been disabled: Unknown device '003826f551042a8b3b7cb06af5760718'[0m
[31m2025-08-03 17:14:26.798 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka bok' failed to setup triggers and has been disabled: Unknown device '16acced44985d5b71c40d48e7caadb66'[0m
[31m2025-08-03 17:14:26.806 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'controller_device': '84f3f3e106b31e8342d085e48f576751', 'integration': 'ZHA', 'controller_entity': 'sensor.przycisk1_action', 'button_up_long_loop': True, 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'brightness_pct': 100}], 'action_button_up_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_increase'}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}], 'action_button_down_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_decrease'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
[31m2025-08-03 17:14:26.813 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'integration': 'ZHA', 'controller_device': '84f3f3e106b31e8342d085e48f576751', 'controller_entity': 'sensor.przycisk1_action', 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'flash': 'short', 'brightness_pct': 100}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
s6-rc: info: service legacy-services: stopping
[33m2025-08-03 17:14:28.400 WARNING (MainThread) [satel_integra.satel_integra] Got exception: 0 bytes read on a total of undefined expected bytes. Most likely the other side has disconnected![0m
[33m2025-08-03 17:14:28.402 WARNING (MainThread) [satel_integra.satel_integra] Got empty response. We think it's disconnect.[0m
[33m2025-08-03 17:14:37.339 WARNING (MainThread) [homeassistant.core] Task <Task pending name='service call background homeassistant.restart' coro=<ServiceRegistry._run_service_call_catch_exceptions() running at /usr/src/homeassistant/homeassistant/core.py:2819> wait_for=<Task pending name='admin service homeassistant.restart' coro=<async_setup.<locals>.async_handle_core_service() running at /usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py:233> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove(), Task.task_wakeup()]> cb=[set.remove()]> was still running after final writes shutdown stage; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown[0m
Found 3 non-daemonic threads.
[15:14:52] INFO: [32mHome Assistant Core finish process exit code 0[0m
[15:14:52] INFO: [32mHome Assistant Core service shutdown[0m
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
[33m2025-08-03 17:15:21.696 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.699 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.700 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.701 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.701 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.702 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.703 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.704 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.705 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.706 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.707 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.708 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:21.709 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:15:35.453 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/aiomusiccast/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
[0m
[31m2025-08-03 17:15:38.585 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Korytarz piƒôtro - przechod√≥wka' failed to setup triggers and has been disabled: Unknown device 'd6c41ce869f30ddc50c06f7d34708a00'[0m
[33m2025-08-03 17:15:38.969 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[33m2025-08-03 17:15:38.973 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api_options.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[33m2025-08-03 17:15:39.834 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning
  warnings.warn(
[0m
[31m2025-08-03 17:15:42.046 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:15:42.276 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[31m2025-08-03 17:15:42.639 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[31m2025-08-03 17:15:42.687 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Jadalnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:15:42.688 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia halogeny' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:15:42.899 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Klatka przechod√≥wka' failed to setup actions and has been disabled: Unknown device '90048d596e6505d2699c9ea5cdc03f68'[0m
[31m2025-08-03 17:15:43.280 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'PKinkiet wiatrolap wejscie' failed to setup actions and has been disabled: Unknown device '4ff87fbffeaff04d6c4136fed22e06c4'[0m
[31m2025-08-03 17:15:43.354 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka prz√≥d' failed to setup actions and has been disabled: Unknown device '58f919db54b4be16b7dc704993322ae1'[0m
[31m2025-08-03 17:15:43.354 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Sypialnia' failed to setup actions and has been disabled: Unknown device '003826f551042a8b3b7cb06af5760718'[0m
[31m2025-08-03 17:15:43.388 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka bok' failed to setup triggers and has been disabled: Unknown device '16acced44985d5b71c40d48e7caadb66'[0m
[31m2025-08-03 17:15:44.390 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'controller_device': '84f3f3e106b31e8342d085e48f576751', 'integration': 'ZHA', 'controller_entity': 'sensor.przycisk1_action', 'button_up_long_loop': True, 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'brightness_pct': 100}], 'action_button_up_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_increase'}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}], 'action_button_down_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_decrease'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
[31m2025-08-03 17:15:44.402 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'integration': 'ZHA', 'controller_device': '84f3f3e106b31e8342d085e48f576751', 'controller_entity': 'sensor.przycisk1_action', 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'flash': 'short', 'brightness_pct': 100}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
[31m2025-08-03 17:15:51.208 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2446, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 641, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2977, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2449, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1975, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 758, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 643, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified[0m
[31m2025-08-03 17:15:51.220 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified') while processing template 'Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.sprawnosc_rekuperatora'[0m
[31m2025-08-03 17:16:02.746 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_bai_ModulationTempDesired_value/config', message: '{'unique_id': 'ebusd_bai_ModulationTempDesired_value', 'device': {'identifiers': 'ebusd_bai', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd bai'}, 'value_template': '{{value_json["value"].value}}', 'state_topic': 'ebusd/bai/ModulationTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'ModulationTempDesired '}'[0m
[31m2025-08-03 17:16:03.099 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc1FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc1FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc1FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc1FlowTempDesired mixermovement'}'[0m
[31m2025-08-03 17:16:03.150 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc2FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc2FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc2FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc2FlowTempDesired mixermovement'}'[0m
[31m2025-08-03 17:16:03.189 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc3FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc3FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc3FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc3FlowTempDesired mixermovement'}'[0m
[33m2025-08-03 17:16:12.757 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:16:13.546 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:16:43.261 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:16:43.264 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:17:12.821 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:17:13.613 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:17:43.262 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:17:43.265 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:18:12.823 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:18:13.609 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[31m2025-08-03 17:18:27.191 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration thessla_green_modbus: No module named 'custom_components.thessla_green_modbus.device_scanner'[0m
[33m2025-08-03 17:18:43.262 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:18:43.264 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:19:12.826 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:19:13.612 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:19:43.265 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:19:43.270 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:20:12.870 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:20:13.663 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:20:43.267 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:20:43.269 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:20:44.168 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning
  warnings.warn(
[0m
[33m2025-08-03 17:21:12.916 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:21:13.702 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:21:22.101 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_deactivationstemplimiter (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['¬∞C', 'K', '¬∞F']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:21:43.268 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:21:43.270 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:22:12.923 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:22:13.721 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:22:43.270 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:22:43.273 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:23:12.929 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:23:13.714 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:23:43.270 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:23:43.273 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:23:51.531 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:23:56.578 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:01.637 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:06.678 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthwc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:11.686 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthwc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:12.995 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:24:13.777 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:24:21.753 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthwc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:26.801 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:32.867 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:36.918 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:41.923 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhwc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:43.271 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:24:43.274 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:24:51.936 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhwc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:24:56.955 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhwc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kJ', 'cal', 'GWh', 'kcal', 'Mcal', 'Gcal', 'MWh', 'mWh', 'TWh', 'Wh', 'J', 'GJ', 'kWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:25:12.010 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_pumppower (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power') it is using; expected one of ['W', 'MW', 'GW', 'TW', 'mW', 'kW']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:25:13.016 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:25:13.796 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:25:27.044 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_returntemp_tempmirror (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['¬∞C', 'K', '¬∞F']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-03 17:25:43.273 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:25:43.275 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:26:13.054 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:26:13.842 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:26:43.275 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:26:43.282 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:27:13.085 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:27:13.873 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:27:43.274 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:27:43.277 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:28:13.139 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:28:13.924 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:28:43.275 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:28:43.277 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:29:13.158 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:29:13.945 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:29:43.276 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:29:43.279 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:29:44.386 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.387 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.388 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.390 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.392 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.393 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.394 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.395 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.419 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.451 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.478 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:44.480 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[31m2025-08-03 17:29:54.811 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/a9d850e.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
    ...<2 lines>...
    )
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/a9d850e.zip[0m
[31m2025-08-03 17:29:54.814 ERROR (MainThread) [custom_components.hacs] [<Integration blakinio/thesslagreen>] Failed to download zipball
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 631, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 677, in download_repository_zip
    raise HacsException(f"[{self}] Failed to download zipball")
custom_components.hacs.exceptions.HacsException: [<Integration blakinio/thesslagreen>] Failed to download zipball[0m
[33m2025-08-03 17:29:58.941 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.946 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.948 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.949 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.950 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.951 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.953 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.954 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.955 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.956 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.957 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.958 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:29:58.959 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:30:13.191 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:30:13.978 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:30:43.279 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:30:43.282 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[31m2025-08-03 17:30:51.926 ERROR (MainThread) [homeassistant.components.analytics] Error sending analytics to https://analytics-api.home-assistant.io/v1: ClientConnectorError(ConnectionKey(host='analytics-api.home-assistant.io', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Multiple exceptions: [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno 111] Connect call failed ('::', 443, 0, 0)"))[0m
[33m2025-08-03 17:31:13.216 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:31:14.015 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:31:43.279 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:31:43.295 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[31m2025-08-03 17:31:48.726 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Korytarz piƒôtro - przechod√≥wka' failed to setup triggers and has been disabled: Unknown device 'd6c41ce869f30ddc50c06f7d34708a00'[0m
[31m2025-08-03 17:31:48.726 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:31:48.728 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Jadalnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:31:48.729 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia halogeny' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:31:48.729 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Klatka przechod√≥wka' failed to setup actions and has been disabled: Unknown device '90048d596e6505d2699c9ea5cdc03f68'[0m
[31m2025-08-03 17:31:48.743 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'PKinkiet wiatrolap wejscie' failed to setup actions and has been disabled: Unknown device '4ff87fbffeaff04d6c4136fed22e06c4'[0m
[31m2025-08-03 17:31:48.745 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka prz√≥d' failed to setup actions and has been disabled: Unknown device '58f919db54b4be16b7dc704993322ae1'[0m
[31m2025-08-03 17:31:48.745 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Sypialnia' failed to setup actions and has been disabled: Unknown device '003826f551042a8b3b7cb06af5760718'[0m
[31m2025-08-03 17:31:48.747 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka bok' failed to setup triggers and has been disabled: Unknown device '16acced44985d5b71c40d48e7caadb66'[0m
[31m2025-08-03 17:31:48.754 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'controller_device': '84f3f3e106b31e8342d085e48f576751', 'integration': 'ZHA', 'controller_entity': 'sensor.przycisk1_action', 'button_up_long_loop': True, 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'brightness_pct': 100}], 'action_button_up_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_increase'}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}], 'action_button_down_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_decrease'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
[31m2025-08-03 17:31:48.761 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'integration': 'ZHA', 'controller_device': '84f3f3e106b31e8342d085e48f576751', 'controller_entity': 'sensor.przycisk1_action', 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'flash': 'short', 'brightness_pct': 100}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
s6-rc: info: service legacy-services: stopping
[33m2025-08-03 17:31:50.217 WARNING (MainThread) [satel_integra.satel_integra] Got exception: 0 bytes read on a total of undefined expected bytes. Most likely the other side has disconnected![0m
[33m2025-08-03 17:31:50.219 WARNING (MainThread) [satel_integra.satel_integra] Got empty response. We think it's disconnect.[0m
[33m2025-08-03 17:31:56.729 WARNING (MainThread) [homeassistant.core] Task <Task pending name='service call background homeassistant.restart' coro=<ServiceRegistry._run_service_call_catch_exceptions() running at /usr/src/homeassistant/homeassistant/core.py:2819> wait_for=<Task pending name='admin service homeassistant.restart' coro=<async_setup.<locals>.async_handle_core_service() running at /usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py:233> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove(), Task.task_wakeup()]> cb=[set.remove()]> was still running after final writes shutdown stage; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown[0m
Found 3 non-daemonic threads.
[15:32:11] INFO: [32mHome Assistant Core finish process exit code 0[0m
[15:32:11] INFO: [32mHome Assistant Core service shutdown[0m
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
[33m2025-08-03 17:32:46.569 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.571 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.572 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.573 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.574 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.575 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.576 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.578 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.579 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.580 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.581 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.582 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:46.583 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-03 17:32:54.931 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/aiomusiccast/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
[0m
[31m2025-08-03 17:33:03.474 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Korytarz piƒôtro - przechod√≥wka' failed to setup triggers and has been disabled: Unknown device 'd6c41ce869f30ddc50c06f7d34708a00'[0m
[33m2025-08-03 17:33:05.721 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[33m2025-08-03 17:33:05.730 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api_options.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[33m2025-08-03 17:33:07.169 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning
  warnings.warn(
[0m
[31m2025-08-03 17:33:08.818 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:33:09.419 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[31m2025-08-03 17:33:09.579 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Jadalnia przechod√≥wka' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:33:09.579 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Kuchnia halogeny' failed to setup triggers and has been disabled: Unknown device '027db707d1a748a24459e1402523ecae'[0m
[31m2025-08-03 17:33:09.597 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[31m2025-08-03 17:33:09.803 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Klatka przechod√≥wka' failed to setup actions and has been disabled: Unknown device '90048d596e6505d2699c9ea5cdc03f68'[0m
[31m2025-08-03 17:33:09.900 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'PKinkiet wiatrolap wejscie' failed to setup actions and has been disabled: Unknown device '4ff87fbffeaff04d6c4136fed22e06c4'[0m
[31m2025-08-03 17:33:09.909 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka prz√≥d' failed to setup actions and has been disabled: Unknown device '58f919db54b4be16b7dc704993322ae1'[0m
[31m2025-08-03 17:33:09.909 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Sypialnia' failed to setup actions and has been disabled: Unknown device '003826f551042a8b3b7cb06af5760718'[0m
[31m2025-08-03 17:33:09.920 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Podbitka bok' failed to setup triggers and has been disabled: Unknown device '16acced44985d5b71c40d48e7caadb66'[0m
[31m2025-08-03 17:33:10.211 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'controller_device': '84f3f3e106b31e8342d085e48f576751', 'integration': 'ZHA', 'controller_entity': 'sensor.przycisk1_action', 'button_up_long_loop': True, 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'brightness_pct': 100}], 'action_button_up_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_increase'}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}], 'action_button_down_long': [{'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'domain': 'light', 'entity_id': 'light.garderoba', 'type': 'brightness_decrease'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
[31m2025-08-03 17:33:10.244 ERROR (MainThread) [homeassistant.components.automation] Blueprint 'Controller - IKEA E1743 TR√ÖDFRI On/Off Switch & Dimmer' generated invalid automation with inputs {'integration': 'ZHA', 'controller_device': '84f3f3e106b31e8342d085e48f576751', 'controller_entity': 'sensor.przycisk1_action', 'action_button_up_short': [{'type': 'turn_on', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light', 'flash': 'short', 'brightness_pct': 100}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': '9182ad8e8d9b8dc01bc13c7bd973aa35', 'entity_id': 'light.garderoba', 'domain': 'light'}]}: Unknown device '9182ad8e8d9b8dc01bc13c7bd973aa35'[0m
[33m2025-08-03 17:33:13.384 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:33:14.106 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[31m2025-08-03 17:33:19.384 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2446, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 641, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2977, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2449, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1975, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 758, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 643, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified[0m
[31m2025-08-03 17:33:19.393 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified') while processing template 'Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.sprawnosc_rekuperatora'[0m
[31m2025-08-03 17:33:40.109 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_bai_ModulationTempDesired_value/config', message: '{'unique_id': 'ebusd_bai_ModulationTempDesired_value', 'device': {'identifiers': 'ebusd_bai', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd bai'}, 'value_template': '{{value_json["value"].value}}', 'state_topic': 'ebusd/bai/ModulationTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'ModulationTempDesired '}'[0m
[31m2025-08-03 17:33:40.558 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc1FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc1FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc1FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc1FlowTempDesired mixermovement'}'[0m
[31m2025-08-03 17:33:40.622 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc2FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc2FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc2FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc2FlowTempDesired mixermovement'}'[0m
[31m2025-08-03 17:33:40.646 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc3FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc3FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc3FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc3FlowTempDesired mixermovement'}'[0m
[33m2025-08-03 17:33:43.281 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:33:43.285 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[31m2025-08-03 17:34:12.356 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration thessla_green_modbus: No module named 'custom_components.thessla_green_modbus.device_scanner'[0m
[33m2025-08-03 17:34:13.322 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:34:14.110 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:34:43.280 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:34:43.282 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:35:13.364 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:35:14.151 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:35:18.740 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning
  warnings.warn(
[0m
[33m2025-08-03 17:35:43.281 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:35:43.285 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:36:13.370 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:36:14.158 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:36:43.282 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:36:43.285 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:37:13.405 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:37:14.187 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:37:43.281 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:37:43.283 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:38:13.423 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:38:14.208 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:38:43.282 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:38:43.285 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:39:13.441 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:39:14.234 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:39:43.283 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:39:43.286 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:40:13.455 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:40:14.239 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-03 17:40:43.300 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:40:43.300 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-03 17:41:13.496 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-03 17:41:14.281 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
